### ISSUE TITLE
Some project stuffs to do this weekend

### ISSUE THREAD

**Issue by asaha1** [arnabsaha1011/mypackse#10]
Song, Joe and Ye,
Please try to find out a solution for our problem individually. Clearly point out the problems that will be solved by your solution and how it solves the problem. We will meet this Tuesday and discuss more. Secondly, configure an IDE of your choice with git. Use pull to download the content. We have to start coding next week.

**Comment by asaha1** [comment]
I know Joe has configured git with C9. For others please complete this part. I have a midterm and 2 assignments due next week so I am taking the weekend off from this project. Also, use Github to indicate how much progress you guys have done. Song and Ye don't have any Github commits as of yet, so try to focus on that as well.

**Comment by YiqiaoXu-Joe** [comment]
I just put my solutions. But it might be changed these days whenever I come up a new idea.

**Comment by sju88** [comment]
I have configured with C9.

**Comment by yemao616** [comment]
I have configured git with Cloud 9.

**Comment by YiqiaoXu-Joe** [comment]
All the solutions can be found in mar16 folder
