### ISSUE TITLE
Solution 1 (Website)

### ISSUE THREAD

**Issue by YiqiaoXu-Joe** [arnabsaha1011/mypackse#11]
The specs are in the mar16 folder
Deadline: 02/21/16

**Comment by YiqiaoXu-Joe** [comment]
http://www.w3schools.com/googleapi/google_maps_basic.asp.
Here is a tutorial of Google Maps API for website.
It seems like javascript API.

**Comment by asaha1** [comment]
Things to do this week:
Layout
Multiple places directions in the map
