### ISSUE TITLE
Solution 2 (Android application)

### ISSUE THREAD

**Issue by YiqiaoXu-Joe** [arnabsaha1011/mypackse#12]
1. Google directions--real path  .A
2. A to B generate the time using straight line   .M
3. generate a straight line(between the places)   .M
4. add more places  .M
5. auto-complete text .A
6. layout   .N
7. Marker to add a place .M
8. Current GPS location .M

.M---March
.A---April
.N---Not sure

The specs are in the mar16 folder
Deadline: 02/21/16

**Comment by asaha1** [comment]
I've made an android application which can search for a location and show using google maps. Next up Itinerary and time addition

**Comment by yemao616** [comment]
1, 2, 3, 4 and 7 had been solved yet.
