### ISSUE TITLE
How to configure multiple projects in this repository?

### ISSUE THREAD

**Issue by asaha1** [arnabsaha1011/mypackse#13]
How to incorporate separate projects, namely sol1, 2 and 3 in the same repo?

**Comment by asaha1** [comment]
Refer to this [link](http://stackoverflow.com/questions/35459877/github-commit-and-import-project-from-a-folder-in-a-repository/35460042#35460042) for solution

**Comment by YiqiaoXu-Joe** [comment]
Each branch seems has everything we have in master branch. That's really bad.

**Comment by asaha1** [comment]
Check out the first solution which is great. You create a separate repo and then create a symbolic link to refer to that repo. Just awesome. I'm using this for sol2.

**Comment by asaha1** [comment]
Finally managed to work on multiple projects under different folders using git shell
