### ISSUE TITLE
Fill up solution 2 part of the slide

### ISSUE THREAD

**Issue by arnabsaha1011** [arnabsaha1011/mypackse#51]
https://docs.google.com/presentation/d/1iMTTqjkAjfIR9KV12kleRVFUgW58u_fqsxpd1sPCLtM/edit#slide=id.p3

**Comment by asaha1** [comment]
@yemao616 Finish this work by today please

**Comment by yemao616** [comment]
done

**Comment by asaha1** [comment]
I added a point to it. Maybe you want to take a look.
