### ISSUE TITLE
Combining the results from the surveys and create charts

### ISSUE THREAD

**Issue by arnabsaha1011** [arnabsaha1011/mypackse#7]
1. Take 20 surveys and make a sheet of the data
2. Create 3 charts
   x vs y
   i. google apps vs no. of users (bar chart)
   ii. laptop/phone vs no of users (bar chart)
   iii. ordering (come up with a good chart)

**Comment by arnabsaha1011** [comment]
Can you update the results from all the surveys onto a file on github?

**Comment by YiqiaoXu-Joe** [comment]
Sure. I'll do it.
